"""init

Revision ID: 056da145035e
Revises: 
Create Date: 2018-08-26 12:50:52.169571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056da145035e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_language_name'), 't_language', ['name'], unique=True)
    op.create_table('t_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_role_name'), 't_role', ['name'], unique=True)
    op.create_table('t_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('picture1_path', sa.String(length=256), nullable=True),
    sa.Column('picture2_path', sa.String(length=256), nullable=True),
    sa.Column('picture3_path', sa.String(length=256), nullable=True),
    sa.Column('video_path', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['t_language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_product_name'), 't_product', ['name'], unique=False)
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_user_name'), 't_user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_name'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_index(op.f('ix_t_product_name'), table_name='t_product')
    op.drop_table('t_product')
    op.drop_index(op.f('ix_t_role_name'), table_name='t_role')
    op.drop_table('t_role')
    op.drop_index(op.f('ix_t_language_name'), table_name='t_language')
    op.drop_table('t_language')
    # ### end Alembic commands ###
