"""change user password column

Revision ID: 1c1096138a91
Revises: 056da145035e
Create Date: 2018-08-26 12:55:35.391891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1096138a91'
down_revision = '056da145035e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('hash_password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'hash_password')
    # ### end Alembic commands ###
