"""update user

Revision ID: 438679e57ed2
Revises: 1c1096138a91
Create Date: 2018-08-31 12:25:01.538108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438679e57ed2'
down_revision = '1c1096138a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_t_user_email'), 't_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_email'), table_name='t_user')
    op.drop_column('t_user', 'email')
    # ### end Alembic commands ###
