"""empty message

Revision ID: b4681c42aa3f
Revises: 
Create Date: 2018-10-14 20:01:33.940626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4681c42aa3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_language', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=64),
               nullable=True)
    op.add_column('t_product', sa.Column('imgs_path', sa.String(length=1024), nullable=True))
    op.alter_column('t_product', 'description',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=2048),
               nullable=True)
    op.alter_column('t_product', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_product', sa.Column('picture1_path', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=2048), server_default=sa.text("''"), nullable=True))
    op.add_column('t_product', sa.Column('picture2_path', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=2048), server_default=sa.text("''"), nullable=True))
    op.add_column('t_product', sa.Column('picture3_path', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=2048), server_default=sa.text("''"), nullable=True))
    op.alter_column('t_product', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=64),
               nullable=False)
    op.alter_column('t_product', 'description',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=2048),
               nullable=False)
    op.drop_column('t_product', 'imgs_path')
    op.alter_column('t_language', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=64),
               nullable=False)
    # ### end Alembic commands ###
